.TH "antroji_praktika::App" 3 "Sun Nov 17 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antroji_praktika::App \- Interaction logic for App\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Application\&.
.SH "Detailed Description"
.PP 
Interaction logic for App\&.xaml 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
