.TH "antroji_praktika::MainWindow" 3 "Sun Nov 17 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antroji_praktika::MainWindow \- Interaction logic for MainWindow\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SH "Detailed Description"
.PP 
Interaction logic for MainWindow\&.xaml 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
