.TH "antroji_praktika::login" 3 "Sun Nov 17 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antroji_praktika::login \- Interaction logic for login\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Window\&.
.SH "Detailed Description"
.PP 
Interaction logic for login\&.xaml 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
