.TH "antroji_praktika::Preke" 3 "Sun Nov 17 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antroji_praktika::Preke \- Interaction logic for Preke\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SH "Detailed Description"
.PP 
Interaction logic for Preke\&.xaml 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
