.TH "antroji_praktika" 3 "Sun Nov 17 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antroji_praktika
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBApp\fP"
.br
.RI "Interaction logic for App\&.xaml "
.ti -1c
.RI "class \fBItems\fP"
.br
.RI "Interaction logic for Items\&.xaml "
.ti -1c
.RI "class \fBlogin\fP"
.br
.RI "Interaction logic for login\&.xaml "
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.RI "Interaction logic for MainWindow\&.xaml "
.ti -1c
.RI "class \fBPreke\fP"
.br
.RI "Interaction logic for Preke\&.xaml "
.ti -1c
.RI "class \fBVisosNekaterizuotosPrekes\fP"
.br
.RI "Interaction logic for VisosNekaterizuotosPrekes\&.xaml "
.ti -1c
.RI "class \fBVisosPrekes\fP"
.br
.RI "Interaction logic for VisosPrekes\&.xaml "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
