.TH "antroji_praktika::Items" 3 "Sun Nov 17 2019" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
antroji_praktika::Items \- Interaction logic for Items\&.xaml  

.SH SYNOPSIS
.br
.PP
.PP
Inherits UserControl\&.
.SH "Detailed Description"
.PP 
Interaction logic for Items\&.xaml 



.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
